### ISSUE TITLE
Publishing addresses for other nodes

### ISSUE THREAD

**Issue by rendaw** [mwarning/KadNode#104]
The FAQ includes
> Can annoucements be made for other nodes? ... No

Assuming I understood that correctly, what are the pros of this decision?  I'm interested in setting up a node and this seems like a really cool project, but here are some things that KadNode can't do because of this that are important use cases for me:

- Publish a website I have on a shared hosting provider which doesn't allow me to install/run software
- Publish addresses for resources on IPFS, DAT, I2P, etc
- Run KadNode on a server that doesn't have an interface with a public address. (edit: when not using upnp)

**Comment by mwarning** [comment]
Thanks for your interest in this side project. :-)

Well, the uses DHT takes the announcements IP address from the senders IP address. Otherwise someone could use the DHT to direct traffic to some target IP address to cause a DOS attack.

While this could be worked around by signing announcements, the BitTorrent DHT forces this approach.

As for the three points you make:
1. I agree, that is not possible.
2. Agreed. The resources must be accessible via the IP address of the server running KadNode. 
3. That is possible (even without upnp). The announcements source IP address is the public IP address of the Internet gateways IP address. So if you have a webserver running on the gateway, or on another server behind the gateway with a port redirect, then that scenario will work.

An alternative approach would be to use a different DHT network to store signed announcements. But that's not what the DHT network KadNode uses can provide (if I am not mistaken).

**Comment by danger89** [comment]
So can KadNode work in combination with IPFS? Can KadNode replace IPNS?

**Comment by mwarning** [comment]
@danger89 it can replace IPNS, but drawback here is that every node you want to reach has to run KadNode as well.

**Comment by mwarning** [comment]
That said, I think the DHT could be modified, to store signed data. But that might create a distinct DHT network (which also would be much faster because it happens to be small).

**Comment by melroy89** [comment]
Ow is it solved? What is the outcome?

**Comment by mwarning** [comment]
@melroy89 well, it cannot be solved with the current DHT (at least not with hacks that would add additional run-trip times). And as I do not have the resources to rewrite the DHT, it won't be supported right now.

**Comment by mwarning** [comment]
I have added a disclaimer that is related: https://github.com/mwarning/KadNode/commit/89190e59c74cf0d0fff2c4aeb0c2225f5850be52
