### ISSUE TITLE
I do not understand how to use it in Internet

### ISSUE THREAD

**Issue by whoizit** [mwarning/KadNode#31]
Need to exchange public keys? How do you imagine that?

**Comment by danger89** [comment]
@mwarning I read your whitepapers & presentations, which also named something about blocking IP's. You can combine some blacklisting together with KadNode (what you propose), you can also use dedicated applictions to help you, such as iptables. Again, this is based on IP's.
Maybe you can also combine blocking with for example a key distribution system. In this situation you will block the public key (not the IP).

Still, be aware changing an IP address as well as generating a new public key is very easy, especially within a decentralized (mesh) network. So blocking an IP-address won't really help that much after all. Another though I just have; you can optionally choose to block domain names. This way people using KadNode can't clame for example 'google.com' within an intranet. If they do claim it, you can tell all KadNode users to block this domain (more as an advise, not mandatory).

**Comment by mwarning** [comment]
@danger89 the DHT in KadNode (and KadNode itself) supports IP address blacklisting already. You can tell KadNode to block an IP address already (e.g. "kadnode-ctl blacklist 1.2.3.4").

Since KadNode has no Key distribution system itself, blocking a key makes no sense for KadNode.
What you propose it a matter for end user applications from my point of view. But I guess we have slightly different ideas here. :-)
