### ISSUE TITLE
kadnode-ctl announce issues

### ISSUE THREAD

**Issue by zciendor** [mwarning/KadNode#90]
1. `kadnode-ctl announce` only shows the sum of announcements, but not what queries/values are exactly announced. That's a bit useless, because the sum of announcements is also given via `kadnode-ctl status`.
I'm not sure if this is how it should be, but without further explanation in the manual, I would expect it lists the announcements in detail.

2. `kadnode-ctl announce <query>` always returns `Invalid port or query too long.`
No matter which arguments you pass to `kadnode-ctl announce` it always returns the same error.
```
$ kadnode-ctl announce test.local
Invalid port or query too long.
```
The usage info says the port is optional...

But even with a port...
```
$ kadnode-ctl announce test.local:6881
Invalid port or query too long.
```
Since no examples are given in the manual for announcements via the command line client it's not clear if or how this is supposed to work at all?
Anyway, the text of the error message is quite confusing. Would be helpful to know what a valid query looks like!?

**Comment by mwarning** [comment]
1. yes, that can certainly be done. How do you expect them to look like?
```
 Query: foo.p2p
   Port: 5667
   Id: abcdef0123456789
 Query: bar.p2p
   Port: 5667
   Id: 0123456789abcdef
2 announcements send.
```
Or is shorter preferable?
```
 Query: foo.p2p
 Query: bar.p2p
2 announcements send.
```
2. The error message is confusing indeed. I will try to improve it.

What is expected for the announce command are queries of the following type:
- a domain (like test.local) where Kadnode already know a certificate for.
- a public base32 key (the one --bob-create-key outputs)
- a base32 or base16 hex string (this will use no authentication at all!)

I could add a mechanism that will hash the string if none of the other formats are detected.
This will also use no authentication at all.
This was not implement, because a mistype might fall into the fallback. But maybe it helps, to have the user add by what means the query is to be parsed and authenticated.
```
announce <bob-auth|tls-auth|base32|base16|hash> <query>
```
Just as an idea. What do you think would be best?

**Comment by zciendor** [comment]
> Or is shorter preferable?

`Id` is internal DHT only, right? No other command uses `id` as an argument?! In this case I would consider shorter better! Maybe display the port as well like:
```
 Query: foo.p2p:6881
 Query: bar.p2p:6881
2 announcements send.
```

> I could add a mechanism that will hash the string if none of the other formats are detected.

That's what I actually expected announce command would do ;-) But maybe add a flag like `-f`, `--force` or `-r`, `--raw`  the user has to explicitely set to push arbitrary data (which is hashed) to the DHT?

**Comment by mwarning** [comment]
Yes, the id is DHT only. The announce command supports giving the id, but the plain query is probably better in many cases.

**Comment by mwarning** [comment]
I hope to have fixed the issues now. Let me know if it now works as expected.
Thanks for all the testing! It's priceless. :-)

**Comment by mwarning** [comment]
2. `announce test.local` is the correct usage. (It is also identical to `test.local.p2p`.)

**Comment by mwarning** [comment]
the issue should be fixed by now. but usability and docs still need improvements.
