### ISSUE TITLE
for Openwrt 

### ISSUE THREAD

**Issue by ysonmezer** [mwarning/KadNode#94]
Hello, can you explain step by step the use of kadnode on openwrt?

**Comment by mwarning** [comment]
1. install KadNode on two nodes:
`opkg update`
`opkg install kadnode`

2. configure one node to announce a domain (let's use a hex key, since it's simplest to explain).
 2.1 create key pair
 ` kadnode --bob-create-key /etc/kadnode_secret.pem`
  remember the public hex key
 2.2 uncomment the bob_load_key line in /etc/config/kadnode
 2.3 restart kadnode:
  `/etc/init.d/kadnode restart`
3. On the other node do
  `ping <public hex key>.p2p`

**Comment by ysonmezer** [comment]
Thank you for your answer. I will try.

**Comment by mwarning** [comment]
Np. Let me know if you run into problems.

**Comment by ysonmezer** [comment]
Hi,
what you mean "On the other node do"
I'm sory. I don't have much experience on this.

**Comment by mwarning** [comment]
KadNode finds the IP address of other nodes running KadNode. One KadNode instance does not make much sense unless you know another node running KadNode or set up your own.

**Comment by ysonmezer** [comment]
OK. I'm just beginning to understand that yet. I'm gonna try to understand the manual. My goal is to access remotely to the transmission application in my router.

**Comment by mwarning** [comment]
The description might need some adjustment.
